import json, re, math, pathlib, hashlib, collections
OUT=pathlib.Path('/mnt/data/forkalope-research')
records=[]
def add(name, domain, product, price, cpu, ram, disks, net, locations, urls, *, amount=None, currency=None, period='month', price_kind='advertised', cores=None, threads=None, ram_gb=None, disk_gb=None, port_mbps=None, transfer_tb=None, unmetered=None, countries=None, location_scope='provider footprint; confirm SKU availability', notes='', group=None, tier='partial', setup=None, tax='Not established; verify checkout', art=None):
    ident=re.sub(r'[^a-z0-9]+','-',name.lower()).strip('-')
    if any(x['id']==ident for x in records): raise ValueError(ident)
    records.append(dict(id=ident,name=name,domain=domain,product=product,price_display=price,
      price=dict(amount=amount,currency=currency,period=period,kind=price_kind,setup_amount=setup,tax_basis=tax),
      cpu=dict(display=cpu,physical_cores_total=cores,hardware_threads_total=threads),
      memory=dict(display=ram,capacity_vendor_gb=ram_gb,byte_basis='vendor GB; not silently converted to GiB'),
      storage=dict(display=disks,raw_capacity_vendor_gb=disk_gb,usable_capacity_gb=None),
      network=dict(display=net,public_port_mbps=port_mbps,included_transfer_tb=transfer_tb,unmetered=unmetered,transfer_scope='See display; not inferred'),
      locations=dict(display=locations,country_codes=countries or [],scope=location_scope),
      source_urls=urls if isinstance(urls,list) else [urls],notes=notes,corporate_or_supply_group=group,
      evidence=tier,research_date='2026-09-16',availability='Advertised; stock and checkout not reserved or transaction-verified',artwork=art or []))

add('Hetzner','hetzner.com','AX42','EUR 79/month indexed starting price; dynamic checkout not captured','AMD Ryzen 7 PRO 8700GE; 8 cores / SMT','64 GB DDR5 ECC','2 × 512 GB NVMe SSD','1 Gbps public port and guaranteed bandwidth; unlimited traffic. Optional 10 Gbps uplink has a different 20 TB outgoing allowance.','HEL1 Helsinki, FI; FSN1 Falkenstein, DE',['https://www.hetzner.com/dedicated-rootserver/ax42/','https://www.hetzner.com/dedicated-rootserver/matrix-ax/'],amount=79,currency='EUR',price_kind='indexed_starting_price_unconfirmed_checkout',cores=8,ram_gb=64,disk_gb=1024,port_mbps=1000,unmetered=True,countries=['FI','DE'],location_scope='Named AX42 locations on product page',notes='Do not put this physical SKU in Hetzner US/Singapore cloud regions. IPv4 can be an extra. Price is provisional, not a firm quotation.')
add('OVHcloud','ovhcloud.com','Eco RISE-1 (US catalog)','USD 70/month + USD 70 setup','Intel Xeon E-2386G; 6 cores / 12 threads','32 GB base; up to 128 GB','2 × 512 GB NVMe base; configurable','1 Gbps public; 1 Gbps private. Transfer policy must be checked against selected country.','US catalog; choose a supported US region in the regional availability matrix',['https://eco.us.ovhcloud.com/rise/','https://us.ovhcloud.com/bare-metal/regions-availability/'],amount=70,currency='USD',cores=6,threads=12,ram_gb=32,disk_gb=1024,port_mbps=1000,countries=['US'],setup=70,notes='Kimsufi and So you Start/Eco are product families, not independent providers. Page may show coming-soon or limited availability. Do not apply EU/US traffic rules to APAC blindly.',group='OVHcloud / Eco / Kimsufi / So you Start',tier='configured')
add('Leaseweb','leaseweb.com','Dedicated Servers / configurable bare metal','Configurator or sales quotation; exact basket not captured','Intel Xeon / AMD configurations; select exact SKU','Configuration dependent','HDD, SSD and NVMe options; quote required','High-bandwidth line: 10/25/40/100 Gbps ports; commit packages can use 95th-percentile billing. Do not treat port as free transit.','Global dedicated-server regions; verify the chosen SKU against country selector',['https://www.leaseweb.com/en/products-services/dedicated-servers','https://www.leaseweb.com/en/products-services/dedicated-servers/high-bandwidth-server','https://kb.leaseweb.com/kb/dedicated-server/dedicated-server-overview/'],price_kind='configurator_not_captured',notes='One provider with many regions. Private interconnect and Internet transit are separate products.')
add('Scaleway','scaleway.com','Dedibox Core-10-XS','EUR 114.74/month equivalent on 36-month commitment','AMD EPYC 8024P; 8 cores / 16 threads; 2.4 GHz','64 GB','2 × 960 GB NVMe','Product family advertises up to 25 Gbps; exact included public/private split requires configuration.','Dedibox locations in France/Europe; select SKU location before mapping',['https://www.scaleway.com/en/dedicated-server/dedicated-power/','https://www.scaleway.com/en/pricing/dedibox/'],amount=114.74,currency='EUR',price_kind='36_month_commitment',cores=8,threads=16,ram_gb=64,disk_gb=1920,notes='Do not mix Dedibox commitment pricing with hourly Elastic Metal. Online.net and Dedibox are not independent suppliers.',group='Scaleway / Dedibox / Online.net',tier='configured')
add('IONOS','ionos.com','L-16 HDD','USD 47/month; cancel anytime','Intel Xeon E3-1230 v6; 4 cores; 3.5–3.9 GHz','16 GB DDR4 ECC','2 × 1 TB SATA HDD; software RAID 1','Unlimited traffic advertised; exact port/region to verify.','Country chosen at order; do not assume every IONOS Cloud region carries this SKU',['https://www.ionos.com/servers/cheap-dedicated-servers','https://www.ionos.com/servers/dedicated-servers'],amount=47,currency='USD',cores=4,ram_gb=16,disk_gb=2000,unmetered=True,tax='State/local taxes may apply',notes='RAID 1 yields approximately 1 TB before filesystem overhead, not 2 TB usable. IONOS dedicated-core Cloud VMs are excluded.',group='IONOS',tier='configured')
add('Contabo','contabo.com','AMD Ryzen 12 Cores','USD 131.75/month promotional; displayed regular USD 179','AMD Ryzen; 12 physical cores','Base memory requires configurator verification','Base disk requires configurator verification','Port, transfer/FUP and regional surcharge require exact-order confirmation.','Dedicated-server region selector; not the same as VPS region availability','https://contabo.com/en-us/dedicated-servers/',amount=131.75,currency='USD',price_kind='promotion_terms_unverified',cores=12,notes='Do not substitute RAM/storage figures from third-party review tables or combine this price with Genoa/Turin configurations.')
add('Worldstream','worldstream.com','Dedicated Servers / Deals','Live inventory or custom quote; exact offer price not captured','Intel/AMD bare-metal configurations','Configuration dependent','Configuration dependent','Port and transit commitment are configurable; capture exact traffic package.','Netherlands dedicated facilities; exact site/SKU to confirm',['https://www.worldstream.com/en/dedicated-servers/','https://www.worldstream.com/en/dedicated-servers/deals/'],price_kind='configurator_not_captured',countries=['NL'],notes='Separate Worldstream customer network/private services from Internet allowance.')
add('DataPacket','datapacket.com','Berlin AMD EPYC 4245P','USD 230/month starting price','AMD EPYC 4245P','Not fixed in retrieved starting-price card','Not fixed in retrieved starting-price card','Dedicated-server family offers unshared 10–200 Gbps; quote binds port, commit and transfer.','Berlin, DE for this price; extensive separate worldwide location catalog',['https://www.datapacket.com/datacenters/berlin','https://www.datapacket.com/dedicated-servers','https://www.datapacket.com/datacenters'],amount=230,currency='USD',price_kind='starting_price_configuration_incomplete',countries=['DE'],location_scope='Price specifically Berlin; worldwide footprint is separate',notes='Other cities have different prices. Tel Aviv offering is physically described in Petah Tikva; do not use city marketing centroid as verified facility coordinates.')
add('Cherry Servers','cherryservers.com','Instant Dedicated Servers','From EUR 0.084/hour advertised family minimum; exact SKU not captured','Physical dedicated CPU; select catalog SKU','Configuration dependent','Configuration dependent','Traffic package depends on plan and region. Spot is a separate preemptible product.','Verify bare-metal location selector, not virtual-server availability',['https://www.cherryservers.com/','https://www.cherryservers.com/bare-metal-dedicated-servers'],amount=.084,currency='EUR',period='hour',price_kind='family_minimum_not_a_configured_offer',notes='A family maximum of 128 cores / 768 GB must not be paired with the minimum hourly price.')
add('Servers.com','servers.com','Enterprise Bare Metal','Sales quotation','Enterprise Intel/AMD configurations; custom','Custom','Custom','Contract-specific connectivity and private networking','Global location catalog; order-specific validation required',['https://www.servers.com/products/enterprise-bare-metal','https://www.servers.com/'],price_kind='quote_only',group='Nexcess branding shown; investigate shared parent with Liquid Web',notes='Current site identifies Servers.com by Nexcess. Do not assume independent corporate failure domain from other Nexcess-branded services.')
add('Latitude.sh','latitude.sh','m4.metal.small','From USD 296/month; regional/billing-mode prices differ','AMD EPYC 4244P; 6 cores; 3.8 GHz','48 GB','2 × 960 GB NVMe','2 × 10 Gbps NIC; 20 TB outbound; incoming unmetered. NIC sum is not guaranteed Internet throughput.','Location-specific pricing selector; Singapore listed separately from global minimum',['https://www.latitude.sh/pricing/m4-metal-small','https://www.latitude.sh/pricing'],amount=296,currency='USD',price_kind='global_starting_price_not_location_quote',cores=6,ram_gb=48,disk_gb=1920,transfer_tb=20,notes='Current product page says 48 GB; an older launch article said 64 GB. Singapore monthly display USD 350 is not the global minimum; annual and hourly modes differ.',tier='configured')
add('Vultr','vultr.com','Bare Metal','Live pricing selector; exact CPU-only offer not captured','Physical CPU SKU; GPU Bare Metal is a separate family','SKU dependent','SKU dependent','Included transfer/port vary by SKU and region.','Bare-metal availability is a subset of Vultr regions',['https://www.vultr.com/products/bare-metal/','https://www.vultr.com/pricing/'],price_kind='configurator_not_captured',notes='Do not substitute Cloud Compute dedicated-vCPU plans for bare metal.')
add('phoenixNAP','phoenixnap.com','Bare Metal Cloud s0.d1.small','USD 0.08/hour; USD 58.40 for a modeled 730-hour month','Intel Xeon E3-1240 v3; 4 cores; 3.4 GHz','16 GB DDR3','2 × 240 GB SSD','2 × 1 Gbps NIC. Initial bandwidth allocation is 15 TB per location pool, 5 TB in Singapore; not per server.','Location must be checked in BMC instance catalog',['https://phoenixnap.com/bare-metal-cloud','https://phoenixnap.com/bare-metal-cloud/instances','https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models'],amount=.08,currency='USD',period='hour',cores=4,ram_gb=16,disk_gb=480,tax='Prices exclude tax',notes='Do not multiply the initial location bandwidth pool by node count. 730-hour monthly value is arithmetic, not a vendor monthly commitment.',tier='configured')
add('Hivelocity','hivelocity.net','Intel Xeon E-2336','USD 75/month base; AMS1 selector displays +USD 55 (USD 130 arithmetic total; verify basket)','Intel Xeon E-2336; 6 cores / 12 threads; 2.9 GHz','32 GB','480 GB SSD','1 Gbps; 20 TB transfer','AMS1 Amsterdam, NL has explicit surcharge; other regions priced separately',['https://www.hivelocity.net/pricing','https://www.hivelocity.net/data-centers/'],amount=75,currency='USD',price_kind='base_before_regional_surcharge',cores=6,threads=12,ram_gb=32,disk_gb=480,port_mbps=1000,transfer_tb=20,countries=['NL'],location_scope='Example selector AMS1; base price is not Amsterdam total',notes='Avoid showing Amsterdam at USD 75. Outlet stock is separate and can disappear.',tier='configured')
add('IBM Cloud','ibm.com','Bare Metal Servers — Classic / VPC','Region/configuration calculator; quotation','Intel Xeon / AMD EPYC, product-dependent','Configuration dependent','Configuration dependent','Classic advertises 20 TB included bandwidth; VPC networking/billing is separate.','Classic and VPC region matrices differ',['https://www.ibm.com/products/bare-metal-servers/pricing','https://www.ibm.com/products/bare-metal-servers','https://cloud.ibm.com/catalog/infrastructure/bare-metal'],price_kind='configurator_not_captured',transfer_tb=20,notes='20 TB applies to Classic description; do not apply automatically to VPC. Procurement and provisioning APIs differ.')
add('OneProvider','oneprovider.com','Paris Atom C2350 dedicated','EUR 7.99/month promotional; displayed regular EUR 11.99; setup promo EUR 0 vs EUR 4.99','Intel Atom C2350; 2 cores / 2 threads; 1.7 GHz','4 GB DDR3','1 × 128 GB SATA SSD','1 Gbps unmetered, subject to fair-use policy','Paris, FR','https://oneprovider.com/',amount=7.99,currency='EUR',price_kind='promotion',cores=2,threads=2,ram_gb=4,disk_gb=128,port_mbps=1000,unmetered=True,countries=['FR'],location_scope='Advertised dedicated offer location',notes='Aggregator/reseller: record actual upstream when known. Other virtual 1-vCPU products on the same page are not physical boxes. Tiny legacy offer is unsuitable as a primary modern build runner.',group='Reseller / upstream operator unknown',tier='configured',setup=0)
add('Clouvider','clouvider.com','Dedicated Servers','Exact live catalog price not captured','Bare-metal configuration dependent','Configuration dependent','Configuration dependent','Network package depends on location/order','Select dedicated-server region; confirm physical SKU','https://www.clouvider.com/',price_kind='configurator_not_captured',tax='Prices exclude VAT',notes='Obtain a fixed basket before including in fleet cost totals.')
add('RedSwitches','redswitches.com','Dedicated / Bare Metal Servers','Sales or configurator quotation','Intel/AMD configurable','Configurable','Configurable','25 Gbps+ and unmetered options advertised; exact included service requires quote','20+ locations advertised; validate dedicated stock for each city','https://www.redswitches.com/',price_kind='quote_or_configurator',notes='Month-to-month and zero-setup claims are product/contract dependent. Record actual facility and upstream separately.')
add('Velia','velia.net','AMD Ryzen 9 7950X3D','EUR 139/month advertised sale','AMD Ryzen 9 7950X3D; 16 cores / 32 threads; 4.2 GHz','128 GB DDR5; vendor memory labeling needs confirmation','2 × 960 GB NVMe','Traffic/port depend on order; not established in retrieved sale card','Germany / US / Singapore offered by provider; selected SKU stock needs confirmation',['https://www.velia.net/gaming/','https://www.velia.net/amd-ryzen-dedicated-server/','https://www.velia.net/dedicated-server/'],amount=139,currency='EUR',price_kind='sale',cores=16,threads=32,ram_gb=128,disk_gb=1920,countries=['DE','US','SG'],notes='Vendor listing refers to DDR5 ECC REG; verify the actual memory implementation on this consumer CPU rather than normalizing it as registered ECC.',tier='configured')
add('IP-Projects','ip-projects.de','Performance Server Ryzen 5 8400F','From EUR 101.46/month','AMD Ryzen 5 8400F','Page conflict: 32 GB in offer body vs 64 GB in another summary','2 × 1 TB NVMe','IPMI advertised; port/traffic not established','German dedicated offering; exact facility/stock requires quote','https://www.ip-projects.de/',amount=101.46,currency='EUR',price_kind='starting_price_with_spec_conflict',disk_gb=2000,countries=['DE'],notes='Keep RAM numeric field null until checkout resolves the 32/64 GB discrepancy.')
add('Avoro','avoro.eu','Ryzen 9000 Dedicated / Instant Dedicated','From EUR 141.92/month excluding VAT for Ryzen 9000 family','Ryzen 9000 family; up to 16 cores / 32 threads, not a fixed base SKU','Up to 256 GB; base not established','Configuration dependent','Instant inventory includes 1 Gbps and 10 Gbps variants; do not combine them.','Frankfurt, DE facility information; exact server selector required',['https://avoro.eu/dedicated-server','https://avoro.eu/en/instant-dedicated','https://avoro.eu/en/datacenter'],amount=141.92,currency='EUR',price_kind='family_minimum_not_a_configured_offer',countries=['DE'],tax='Excludes VAT',notes='Avoro Rootserver/Power Rootserver is not the same as this physical Dedicated line.')
add('Keyweb','keyweb.de','Dedicated Server','From EUR 74/month; exact configuration not captured','Configuration dependent','Configuration dependent','Configuration dependent','Managed service/root access advertised; network allowance requires quote','Germany','https://www.keyweb.de/',amount=74,currency='EUR',price_kind='family_minimum_not_a_configured_offer',countries=['DE'])
add('myLoc / servdiscount','servdiscount.com','servdiscount dedicated inventory','Live inventory price; exact basket not captured','Fixed physical configurations','Fixed per offer','Fixed per offer','Network conditions require exact inventory row','Düsseldorf, DE','https://servdiscount.com/',price_kind='configurator_not_captured',countries=['DE'],location_scope='Provider identifies Düsseldorf for these servers',notes='Group myLoc, servdiscount and webtropia for supplier concentration analysis; do not count them as three unrelated networks.',group='myLoc / servdiscount / webtropia')
add('Fasthosts','fasthosts.co.uk','Dedicated Servers','Exact dedicated price not captured','Configuration dependent','Configuration dependent','Configuration dependent','Dedicated order network terms required','UK dedicated offering; verify exact data centre','https://www.fasthosts.co.uk/',price_kind='configurator_not_captured',countries=['GB'],notes='Treat corporate-parent independence as unresolved until procurement checks it.')
add('UKServers','ukservers.com','cPanel 270','From GBP 124/month','Intel Xeon E-2488; 8 cores; 3.2 GHz','32–128 GB ECC; base tier 32 GB','Up to 2 SSD/HDD + 2 M.2 NVMe; installed base drives not specified','1 Gbps or 10 Gbps options; included transfer not captured; IPMI','UK facilities; exact location via order','https://www.ukservers.com/baremetal-server/cpanel-servers/',amount=124,currency='GBP',price_kind='starting_price_configuration_incomplete',cores=8,ram_gb=32,countries=['GB'],notes='cPanel-focused offering may include licensing/management. Ask for an unmanaged Linux equivalent rather than assuming identical price.')
add('RapidSwitch','rapidswitch.com','AMD dedicated family','From GBP 47.95/month; specific SKU not captured','AMD dedicated; configurable','Configuration dependent','Configuration dependent','Contract/order-specific port and transfer','UK locations advertised include Maidenhead, Gosport, Glasgow; separate Dallas US offer starts GBP 160','https://www.rapidswitch.com/',amount=47.95,currency='GBP',price_kind='family_minimum_not_a_configured_offer',countries=['GB','US'],notes='Do not use the UK family minimum as a Dallas quote.')
add('Namecheap','namecheap.com','Dedicated Server catalog','Advertises from USD 44.88/month; promotions and annual equivalents vary','Physical dedicated configurations; exact SKU needed','SKU dependent','SKU dependent','Bandwidth varies by chosen fixed plan','US dedicated offering; confirm exact order location','https://www.namecheap.com/hosting/dedicated-servers/our-prices/',amount=44.88,currency='USD',price_kind='family_minimum_not_a_configured_offer',countries=['US'],notes='Full root requires User-Responsible or Basic management. Hardware upgrades mean changing plan, not arbitrary live RAM additions.')
add('NovoServe','novoserve.com','Dedicated / unmetered servers','1 Gbps unmetered configurations advertised above EUR 100/month; exact SKU quote','Intel Xeon / AMD EPYC; configurable','Configurable','NVMe / SSD / HDD options','Standard 25 TB outbound with free incoming; unmetered 1–50 Gbps alternatives are different packages','Netherlands, Denmark, US advertised; verify SKU location',['https://novoserve.com/dedicated-servers','https://novoserve.com/dedicated-server','https://novoserve.com/blog/ai-dedicated-servers-with-fixed-monthly-pricing'],price_kind='quote_or_configurator',transfer_tb=25,countries=['NL','DK','US'],notes='Do not conflate 25 TB metered standard with separately priced unmetered transit.')
add('NFOrce','nforce.com','HP DL320e v2 Budget 1','EUR 49.99/month excluding VAT; standard 12-month auto-renewing contract','Intel Xeon E3-1240 v3; 4 cores / 8 threads; 3.4–3.8 GHz','16 GB','2 × 2 TB SATA HDD','1 Gbps dedicated; 10 TB outgoing; incoming unmetered/free','NL-1 Databarn Amsterdam; NL-3 Nedzone Steenbergen, NL','https://www.nforce.com/',amount=49.99,currency='EUR',price_kind='12_month_contract',cores=4,threads=8,ram_gb=16,disk_gb=4000,port_mbps=1000,transfer_tb=10,countries=['NL'],tax='Excludes VAT',notes='Site states own hardware, not reseller. Exact stock/site must still be selected.',tier='configured')
add('AltusHost','altushost.com','Dedicated Servers','Sales/configurator quotation','Configuration dependent','Configuration dependent','Configuration dependent','Quote required','European provider; physical location must be verified for selected server','https://altushost.com/',price_kind='quote_or_configurator')
add('HOSTKEY','hostkey.com','AMD EPYC 9354 dedicated offer','From EUR 299/month advertised','AMD EPYC 9354; 32 cores; 3.25 GHz','192 GB','2 × 1 TB NVMe','10 Gbps; 50 TB transfer','Location selection required; provider advertises NL, FI, US and additional markets','https://hostkey.com/',amount=299,currency='EUR',price_kind='starting_price',cores=32,ram_gb=192,disk_gb=2000,port_mbps=10000,transfer_tb=50,notes='Do not use bm.v/vCPU-marked products as evidence of a complete physical host. Confirm the selected EPYC listing is single-tenant full hardware.',tier='configured')
add('FDCServers','fdcservers.net','Unmetered Dedicated Servers','From USD 129/month; base hardware not captured','AMD EPYC / Intel Xeon options','Configuration dependent','Configuration dependent','10–200 Gbps unmetered family; advertised no data cap, throttling or FUP. Exact port must be priced.','23 locations advertised; dedicated selector needed',['https://fdcservers.net/product/unmetered-dedicated-servers','https://fdcservers.net/'],amount=129,currency='USD',price_kind='family_minimum_not_a_configured_offer',unmetered=True,notes='Do not infer physical-server locations from FDC VPS availability.')
add('Aruba','arubacloud.com','AV-A205.1','EUR 110.68/month + VAT','AMD Ryzen 5 9600X; 6 cores; 3.9–5.4 GHz','32 GB DDR5 on-die ECC','2 × 500 GB NVMe','1 Gbps; unlimited traffic','Arezzo and Bergamo, IT',['https://www.arubacloud.com/dedicated-servers-range/','https://aruba.it/en/server-price-list.aspx'],amount=110.68,currency='EUR',cores=6,ram_gb=32,disk_gb=1000,port_mbps=1000,unmetered=True,countries=['IT'],location_scope='Product row lists these locations',tax='Excludes VAT',notes='DDR5 on-die ECC is not proof of end-to-end server ECC. SeFlow is another Aruba line, not independent. Lower-priced RD-I101 has 25 TB/month, not unlimited.',group='Aruba / SeFlow',tier='configured')
add('IKOULA','ikoula.com','Regen S1','EUR 180/month regular; EUR 150/month promotion code IKREGEN30; excluding VAT','2 × Intel Xeon Silver 4214R; total 24 cores / 48 threads','128 GB DDR4 ECC REG','2 × 960 GB enterprise NVMe; software RAID','Shared 1 Gbps public; 100 Mbps guaranteed; unlimited traffic','France',['https://www.ikoula.com/en/dedicated-server/regen','https://www.ikoula.com/en/dedicated-server'],amount=180,currency='EUR',cores=24,threads=48,ram_gb=128,disk_gb=1920,port_mbps=1000,unmetered=True,countries=['FR'],tax='Excludes VAT',notes='Use EUR 180 for non-promotional cost scenarios; code price may expire. Do not count 1 Gbps as committed bandwidth.',tier='configured')
add('Nine','nine.ch','Root Dedicated Server','CHF 233/month + CHF 250 setup','AMD EPYC 7313P; 16 cores','32 GB base; expandable','Disk details require full configuration','Included transit details require confirmation','Zurich, CH; provider describes two independent data centres',['https://docs.nine.ch/docs/root-server/','https://nine.ch/en/price-calculator/'],amount=233,currency='CHF',cores=16,ram_gb=32,countries=['CH'],setup=250,notes='Managed Dedicated is a different, higher-priced service; do not substitute managed price or disks without validating the root configuration.')
add('GleSYS','glesys.com','X11-1','EUR 265/month (also SEK 2,665 listed), excluding VAT','Intel Xeon Gold 6132; 14 cores / 28 threads','64 GB','2 × 480 GB SATA SSD','10 Gbps port; transfer entitlement must be confirmed separately','Falkenberg and Stockholm, SE',['https://glesys.com/pricing/','https://glesys.com/products/bare-metal/dedicated-servers/'],amount=265,currency='EUR',cores=14,threads=28,ram_gb=64,disk_gb=960,port_mbps=10000,countries=['SE'],location_scope='Exact X11-1 row locations',tax='Excludes VAT',notes='Other GleSYS SKUs offer Oulu FI or Oslo NO, but do not propagate those locations to X11-1.',tier='configured')
add('M247 Global','m247global.com','Dedicated Servers','Sales quotation','Enterprise configurable bare metal','Custom','Custom','Custom connectivity/commit','Global footprint; facility and SKU need sales confirmation','https://www.m247global.com/dedicated-server',price_kind='quote_only')
add('GTHost','gthost.com','Supermicro Blade Xeon D-1531','USD 59/month; USD 5/day trial is separate','Intel Xeon D-1531; 6 cores / 12 threads; 2.2–2.7 GHz','16 GB DDR4-2133','480 GB SSD','300 Mbps unmetered; IPMI','US catalog; exact city selected at order','https://gthost.com/dedicated-server-usa/',amount=59,currency='USD',cores=6,threads=12,ram_gb=16,disk_gb=480,port_mbps=300,unmetered=True,countries=['US'],notes='Do not confuse daily trial pricing with a daily production billing plan.',tier='configured')
add('ServerMania','servermania.com','AMD EPYC 4124P entry configuration','USD 139/month in provider pricing guide dated July 14, 2026','AMD EPYC 4124P','32 GB','1 TB; media type not established in retrieved excerpt','1 Gbps; one usable IPv4; transfer cap needs quote','Location must be selected; article price is not a regional inventory guarantee','https://www.servermania.com/kb/articles/dedicated-server-hosting-pricing',amount=139,currency='USD',price_kind='provider_guide_example_not_checkout',ram_gb=32,disk_gb=1000,port_mbps=1000,notes='Linux example. Treat the article as a published example, not a guaranteed purchasable basket.',tier='configured')
add('ReliableSite','reliablesite.net','Dedicated Server catalog','Exact current SKU price not captured','Physical Intel / AMD configurations','SKU dependent','SKU dependent','Metal+ is a USD 99/year add-on advertising 10 Gbps and extra IPv4 benefits; do not assume free 10 Gbps on every order','US locations; confirm SKU and selected city','https://www.reliablesite.net/',price_kind='configurator_not_captured',countries=['US'])
add('InterServer','interserver.net','Dedicated Servers','Exact current physical SKU not captured','Intel / AMD configurable','Configurable','Configurable','Order-dependent transfer and port','US; exact dedicated location to confirm','https://www.interserver.net/',price_kind='configurator_not_captured',countries=['US'])
add('Liquid Web','liquidweb.com','Managed Dedicated Servers','Sales/configurator quotation','Physical managed dedicated hardware','Configuration dependent','Configuration dependent','Managed-service network package depends on contract','Dedicated region selector; not all cloud locations apply','https://www.liquidweb.com/',price_kind='quote_or_configurator',group='Nexcess branding shown; check relation to Servers.com',notes='Managed software/support can inflate comparisons against unmanaged Hetzner. Quote an equivalent Linux-only configuration.')
add('OpenMetal','openmetal.io','Bare Metal','Pricing table/configurator; exact basket not captured','Enterprise bare metal; select hardware class','Configuration dependent','Configuration dependent','Network package depends on hardware/contract','US East, US West and Europe listed',['https://openmetal.io/bare-metal-pricing/','https://openmetal.io/'],price_kind='configurator_not_captured',notes='Bare-metal rental and multi-node hosted private cloud are different units of purchase; do not divide a cluster price by an assumed node count.')

add('Wholesale Internet','wholesaleinternet.net','Dual Xeon E5-2660 custom dedicated','USD 64/month; free setup','2 × Xeon E5-2660; total 16 cores / 32 threads','32 GB ECC','480 GB SSD','1 Gbps unmetered; 5 IPv4; IPv6 /64','Kansas City, Missouri, US',['https://www.wholesaleinternet.net/custom_dedicated/','https://www.wholesaleinternet.net/'],amount=64,currency='USD',cores=16,threads=32,ram_gb=32,disk_gb=480,port_mbps=1000,unmetered=True,countries=['US'],setup=0,tier='configured',notes='Legacy hardware; power efficiency and single-thread performance differ substantially from modern EPYC/Ryzen.')
add('Dacentec','dacentec.com','Supermicro 8-bay dual E5-2650 v2','USD 80/month in current billing inventory','2 × Intel Xeon E5-2650 v2','128 GB','240 GB SSD + 2 × 3 TB HDD','1 Gbps dedicated family; included transfer not captured','Lenoir, North Carolina, US; exact inventory facility must be confirmed',['https://dacentec.com/hostbill/','https://billing.dacentec.com/hostbill/index.php?%2Fcart=&action=add&cat_id=3&id=428'],amount=80,currency='USD',ram_gb=128,disk_gb=6240,port_mbps=1000,countries=['US'],notes='The billing URL contains an unavailable older selected item but also current inventory rows; this record describes the listed Supermicro offer, not that unavailable Opteron. Some other plans are rent-to-own.',tier='configured')
add('Database Mart / Server Mart','databasemart.com','Lite Dedicated SSD','USD 41/month recurring promotion; regular USD 49','Intel Xeon E3-1220; 4 cores','16 GB','480 GB SSD + 500 GB SATA disk','100 Mbps unmetered; 1 IPv4','US; Dallas advertised, exact order facility to verify',['https://www.databasemart.com/pricing','https://www.databasemart.com/dedicated-hosting'],amount=41,currency='USD',price_kind='recurring_promotion',cores=4,ram_gb=16,disk_gb=980,port_mbps=100,unmetered=True,countries=['US'],setup=0,tier='configured',group='Database Mart / Server Mart',notes='Do not confuse server-mart.com with unrelated similarly named providers. SSD plus SATA auxiliary disk is not a mirrored pair.')
add('Colocation America','colocationamerica.com','Intel Xeon E3-1270 v6 dedicated','USD 135/month','Xeon E3-1270 v6; 4 cores / 8 threads; 3.8 GHz','Up to 64 GB; base allocation not established','Up to 4 drives; base drives not established','1 Gbps; 15 TB transfer; free setup','Los Angeles, California, US',['https://www.colocationamerica.com/dedicated-servers-all','https://www.colocationamerica.com/dedicated-servers'],amount=135,currency='USD',cores=4,threads=8,port_mbps=1000,transfer_tb=15,countries=['US'],setup=0,notes='The catalog reports maxima, not necessarily included RAM or disk. A separate E3-1220 row has a suspicious thread count; that row is not normalized here.')
add('Tier.Net','tier.net','Single Intel E3-1270 v6 dedicated','Exact SKU price requires order; family from USD 49.95 is not this configuration','Xeon E3-1270 v6; 4 cores; 3.8–4.2 GHz','64 GB DDR4','500 GB SSD','10 Gbps port; 20 TB transfer','Ashburn VA; Bend OR; Binghamton NY; Charlotte NC; Dallas TX; New York NY, US','https://www.tier.net/dedicated-server-hosting',price_kind='configurator_not_captured',cores=4,ram_gb=64,disk_gb=500,port_mbps=10000,transfer_tb=20,countries=['US'],notes='Managed support is a separate add-on. Do not equate 10 Gbps access with 10 Gbps sustained unmetered Internet.')
add('HostDime','hostdime.com','Self-managed Xeon E3-1230 v5','USD 129/month','Xeon E3-1230 v5; 4 cores / 8 threads; 3.4 GHz','16 GB','480 GB SSD OR 1 TB SATA3 HDD','1 Gbps burstable uplink; advertised 75 Mbps (~25 TB) monthly bandwidth; verify measurement/billing method','US offer; separate dedicated catalogs in Brazil, Mexico, UK, Colombia and India','https://www.hostdime.com/self-managed-dedicated-servers',amount=129,currency='USD',cores=4,threads=8,ram_gb=16,disk_gb=480,port_mbps=1000,countries=['US','BR','MX','GB','CO','IN'],notes='Normalized disk selects the SSD option. Do not interpret the approximate 25 TB as an independently verified metered allowance. Do not count announced Mexico 2028 facility as operating.',tier='configured')
add('RackNerd','racknerd.com','Intel Xeon E3-1230 v2 bare metal','USD 139/month; optional 15OFFDEDI promotion requires checkout','Intel Xeon E3-1230 v2','16 GB','480 GB SSD','1 Gbps; 35 TB; 5 IPv4; IPMI/KVM','US table; choose exact city in order form','https://www.racknerd.com/dedicated-servers',amount=139,currency='USD',ram_gb=16,disk_gb=480,port_mbps=1000,transfer_tb=35,countries=['US'],tier='configured',notes='Hybrid Dedicated is a different virtualized product and excluded. Separate 160 TB storage special is USD 479/month in Los Angeles DC-02.')
add('LumaDock','lumadock.com','BM.E1 / HPE ProLiant DL360 Gen9','USD 119/month promotional; displayed regular USD 159; billing selector/commitment must be checked','2 × Xeon E5-2680 v3; total 24 cores / 48 threads; 2.5 GHz','64 GB DDR4 ECC','3 × 2 TB SSD','1 Gbps unmetered; IPv4/IPv6; iLO','London GB; Frankfurt DE; New York US; Amsterdam NL; Paris FR; Madrid ES','https://lumadock.com/dedicated-servers',amount=119,currency='USD',price_kind='promotion_billing_term_needs_confirmation',cores=24,threads=48,ram_gb=64,disk_gb=6000,port_mbps=1000,unmetered=True,countries=['GB','DE','US','NL','FR','ES'],setup=0,tier='configured',notes='Milan marked SOON is not included. Exact city/SKU availability and annual selector effect must be verified.')
add('Gcore','gcore.com','Hong Kong Xeon E-2136 dedicated','USD 158/month','Intel Xeon E-2136','32 GB','2 × 2 TB SATA; hardware RAID','1 Gbps; 5 TB/month','Hong Kong, HK','https://gcore.com/hosting/dedicated/hong-kong',amount=158,currency='USD',ram_gb=32,disk_gb=4000,port_mbps=1000,transfer_tb=5,countries=['HK'],location_scope='Exact regional product page',tier='configured',notes='Gcore Cloud minute-billed bare metal is a separate purchase path; do not combine its EUR prices with this hosting offer.')
add('Zenlayer','zenlayer.com','S-Series Bare Metal Cloud','From USD 0.587/hour; selected monthly promotional locations from USD 77 are separate','Intel Xeon E-series range; 4–8 cores; 3.5–3.9 GHz','16–32 GB range; exact base not captured','SATA or SSD; exact capacity requires selected SKU','Monthly plans may include 10–50 Mbps flat or 1.5–7.5 TB by location; 95th-percentile plans also exist','Global edge locations; order-specific bare-metal location selector',['https://www.zenlayer.com/bare-metal/','https://docs.console.zenlayer.com/welcome/pricing/bare-metal-cloud-pricing'],amount=.587,currency='USD',period='hour',price_kind='family_minimum_not_a_configured_offer',notes='Do not pair all maximum hardware/network values with the minimum price. Cloud USD 8.03 offerings are VMs, not these physical servers.')
add('Exabytes','exabytes.my','Economy Self-Managed Dedicated','MYR 515.90/month + MYR 500 setup','Single Intel Xeon E3; 4 cores; exact model not specified','16 GB','2 × 1 TB NL-SAS; RAID 1','100 Mbps unmetered; shared/constant wording differs on page; 2 IPv4','Cyberjaya, Malaysia','https://www.exabytes.my/servers/dedicated-server',amount=515.9,currency='MYR',cores=4,ram_gb=16,disk_gb=2000,port_mbps=100,unmetered=True,countries=['MY'],setup=500,tier='configured',notes='Do not assume a 100 Mbps committed dedicated circuit from the shared-port wording. Managed tiers and larger setup fees are different offers.')
add('IP ServerOne','ipserverone.com','Single NVIDIA RTX 4090 dedicated GPU server','From MYR 2,099/month + 8% SST','AMD EPYC 7313; 16 cores; 3 GHz; 1 × RTX 4090 24 GB GPU','64 GB','1 × 3.8 TB NVMe / SSD; exact interface to confirm','300 Mbps; transfer allowance not established','Malaysia offering; confirm GPU facility; general bare metal also has Singapore locations',['https://www.ipserverone.com/pricing/','https://www.ipserverone.com/gpu-servers/','https://www.ipserverone.com/bare-metal/'],amount=2099,currency='MYR',price_kind='starting_price',cores=16,ram_gb=64,disk_gb=3800,port_mbps=300,countries=['MY'],tax='Excludes 8% SST',tier='configured',notes='Page says software RAID 1 while listing a single disk: treat RAID/usable capacity as unresolved. Use MYR, not the illustrative USD conversion at 4.4 MYR/USD. Nova GPU VM is excluded.')
add('E2E Networks','e2enetworks.com','Dedicated / Bare Metal Servers','Current quote required after July/August 2026 pricing changes','Physical CPU/GPU configurations; quote exact host','Quote','Quote','Quote port, egress and cross-region charges','India; selected dedicated region must be quoted','https://docs.e2enetworks.com/docs/myaccount/billing/pricing-update-july-2026/',price_kind='quote_only',countries=['IN'],notes='Provider pricing-change notice directs dedicated/bare-metal customers to account managers. Do not use pre-change rates or VM prices.')
add('Voyager','voyager.nz','Low dedicated — 32 GB','NZD 365/month + GST','2 CPUs; 16 total cores; exact model not given','32 GB','2 × 1 TB SSD','Unmetered subject to fair-use policy; port speed not specified','Auckland, New Zealand','https://voyager.nz/business/hosting/dedicated-servers',amount=365,currency='NZD',cores=16,ram_gb=32,disk_gb=2000,unmetered=True,countries=['NZ'],tax='Excludes GST',tier='configured',notes='64 GB variant is NZD 375/month. This is the physical dedicated service, not the cloud-server line.')
add('xneelo','xneelo.co.za','TruServ Plus 2336','ZAR 1,995/month + ZAR 695 setup; VAT inclusive','Xeon E-2336; 6 cores / 12 threads; 2.9–4.8 GHz','32 GB ECC','2 × 1 TB enterprise SSD; software RAID 1','Unlimited subject to AUP; exact public port must be confirmed','South Africa; selected TruServ facility must be confirmed','https://xneelo.co.za/dedicated-servers/',amount=1995,currency='ZAR',cores=6,threads=12,ram_gb=32,disk_gb=2000,unmetered=True,countries=['ZA'],setup=695,tax='Includes VAT',tier='configured',notes='Use self-managed TruServ for full control. Do not mislabel old Hetzner South Africa/xneelo photographs as the German Hetzner fleet.')
add('HOSTAFRICA','hostafrica.com','Metal Core Linux 8','USD 140.84/month advertised; confirm billing currency','8 physical cores / 16 threads; exact CPU model not captured','Requires product configuration','Requires product configuration','Requires product configuration','African dedicated service; exact country/SKU needs order confirmation','https://www.hostafrica.com/servers/dedicated-servers/',amount=140.84,currency='USD',cores=8,threads=16,notes='VDS rows on the same page are virtual and excluded. Do not infer dedicated locations from the entire VPS footprint.')
add('EdgeUno','edgeuno.com','Bare Metal','From USD 695/month; custom host configuration','Custom Intel / AMD physical hardware','Custom','Custom','Custom bandwidth/commit; exact allowance needs quote','Dedicated/cloud footprint includes Argentina, Brazil, Chile, Colombia, Ecuador, Mexico and Peru; additional US/Europe locations',['https://edgeuno.cloud/','https://edgeuno.com/bare-metal/','https://edgeuno.com/the-enterprise-guide-to-edge-data-centers-for-latin-america-enterprises/'],amount=695,currency='USD',price_kind='family_minimum_not_a_configured_offer',countries=['AR','BR','CL','CO','EC','MX','PE'],notes='45+ sites is a provider network claim, not 45 confirmed locations for every bare-metal configuration. VPS prices are not dedicated prices.')
add('Bacloud','bacloud.com','Epyc U33 customizable dedicated','EUR 187/month; minimum one month','AMD EPYC 7002 series; exact processor selected in configurator','Up to 2 TB; base RAM unknown','Chassis supports 4 NVMe + 3 HDD/SSD positions; included drives unknown','Up to 10 Gbps; exact port and transfer package require configuration','Lithuania for this dedicated page; separate Netherlands bare-metal offerings',['https://www.bacloud.com/en/dedicated-servers','https://www.bacloud.com/en/our-datacenter/lithuania'],amount=187,currency='EUR',price_kind='starting_price_configuration_incomplete',countries=['LT','NL'],setup=0,notes='Capacity maxima and chassis drive bays are not included RAM/disks. Free setup advertised. Own Lithuanian facility provides useful real data-centre artwork.')
add('Arsys','arsys.net','Dedicated Servers','Pay-per-use/configurator quotation','Configurable physical dedicated hardware','Configurable','Configurable','1 Gbps; unlimited traffic advertised','Spain; exact site and selected configuration to confirm',['https://www.arsys.net/servers/dedicated','https://www.arsys.net/'],price_kind='quote_or_configurator',port_mbps=1000,unmetered=True,countries=['ES'],notes='Do not treat a provider landing-page starting price as a priced configuration. Investigate corporate affiliation before counting as independent from IONOS.')
add('Sakura Internet','sakura.ad.jp','Sakura PHY dedicated servers','Current PHY configurator/quotation; no reliable matched price captured','Current PHY physical-server configurations','Configure','Configure','Configure bandwidth and transfer','Japan; exact PHY site must be selected','https://server.sakura.ad.jp/',price_kind='configurator_not_captured',countries=['JP'],notes='Older Sakura dedicated generations have separate end-of-sale/end-of-service notices. Do not assume they describe current PHY availability, or use old-generation prices.')
add('Kagoya','kagoya.jp','KAGOYA FLEX Bare Metal','Sales/configurator quotation','Physical dedicated KAGOYA FLEX configurations','Configure','Configure','Contract-specific network package','Japan; facility and SLA to confirm','https://www.kagoya.jp/',price_kind='quote_only',countries=['JP'],notes='KAGOYA FLEX bare metal is the relevant family. Old managed-hosting campaign prices are not used as a physical-server quotation.')
add('IDC Frontier','idcf.jp','IDCF Cloud Bare Metal','Official specification/pricing page; exact current basket not captured','Physical cloud bare-metal configuration','Configure','Configure','Confirm interface, shared versus guaranteed bandwidth and traffic billing','Japan; select bare-metal region','https://www.idcf.jp/cloud/baremetal/price/',price_kind='configurator_not_captured',countries=['JP'])
add('Servers Australia','serversaustralia.com.au','Value Dedicated / Enterprise HPE ProLiant DL365 Gen11','Value family from AUD 99/month ex GST; selected hardware and other landing pages differ','Value: SKU dependent; Enterprise includes HPE ProLiant DL365 Gen11 options','Configuration dependent','Configuration dependent','Family advertises 2 × 10 Gbps switch ports; Internet entitlement is separate','Sydney SY3/SY4; Brisbane BR1; Melbourne ME1; Perth PE2, AU',['https://www.serversaustralia.com.au/products-services/dedicated-servers','https://www.serversaustralia.com.au/marketplace/buy-dedicated-servers'],amount=99,currency='AUD',price_kind='family_minimum_not_a_configured_offer',countries=['AU'],tax='Excludes GST',notes='Do not pair the AUD 99 Value minimum with the Enterprise Gen11 hardware. Other site pages show different starting prices; marketplace basket controls.')
add('Digital Pacific','digitalpacific.com.au','Dedicated Servers','Current configuration quotation','Physical dedicated family; exact model required','Configure','Configure','Verify transfer, public port and overage','Australia; exact dedicated facility to confirm','https://www.digitalpacific.com.au/',price_kind='configurator_not_captured',countries=['AU'])
add('RansomIT','ransomit.com.au','Dedicated server location-specific inventory','Live billing catalog; exact SKU price not captured','Physical dedicated inventory; choose exact SKU','SKU dependent','SKU dependent','Location/SKU-specific transfer and port','Melbourne, Sydney, Adelaide, Perth, Brisbane AU; Auckland NZ; Tokyo JP; Singapore SG',['https://www.ransomit.com.au/','https://secure.ransomit.com.au/'],price_kind='configurator_not_captured',countries=['AU','NZ','JP','SG'],notes='Billing catalog defaults to USD in retrieved view; AUD is a separate selector. Never label a displayed dollar amount AUD without checking.')
add('DonWeb','donweb.com','Servidores Dedicados','Current catalog/configurator; exact basket not captured','Physical dedicated servers; exact configuration required','Configure','Configure','Verify included transfer, port and international connectivity','Latin American service; exact physical site must be confirmed, not inferred from customer country',['https://donweb.com/en-int/servidores-dedicados','https://donweb.com/'],price_kind='configurator_not_captured',notes='Keep physical dedicated offers separate from cloud/VPS and Proxmox virtual packages. Country remains unknown until the dedicated order location is verified.')
add('Afrihost','afrihost.com','Bronze Self-Managed Dedicated','ZAR 1,350/month; free setup','Intel Xeon E3-1230; 4 cores; 3.2 GHz','8 GB DDR3 1333 MHz','2 × 1 TB enterprise disks; RAID 1','1 Gbps; unlimited traffic subject to terms','South Africa; exact hosting facility to confirm','https://www.afrihost.com/dedicated-hosting',amount=1350,currency='ZAR',cores=4,ram_gb=8,disk_gb=2000,port_mbps=1000,unmetered=True,countries=['ZA'],setup=0,tier='configured',notes='Month-to-month. Provider retains hardware ownership; this is rental, not colocation or purchased hardware.')

add('Amazon Web Services','aws.amazon.com','EC2 m7i.metal-24xl','Region-specific hourly On-Demand price; exact primary-source price not captured','4th-generation Intel Xeon Scalable; 96 vendor vCPUs, not 96 physical cores','384 GiB','EBS-only; no included local instance store','37.5 Gbps instance network; 30 Gbps EBS bandwidth. Internet egress and EBS are separately billed.','Only regions offering this exact .metal instance type',['https://aws.amazon.com/ec2/instance-types/m7i/','https://docs.aws.amazon.com/ec2/latest/instancetypes/gp.html','https://aws.amazon.com/ec2/pricing/on-demand/'],price_kind='regional_rate_not_captured',notes='Only the .metal SKU is physical bare metal. Ordinary EC2 instances, dedicated tenancy and Dedicated Hosts are different products. Never treat internal network bandwidth as included Internet transit.')
add('Oracle Cloud','oracle.com','BM.Standard.E5.192','Current compute, memory and network rate quotation required','AMD EPYC 9J14; 192 vendor OCPUs; 2.4–3.7 GHz','2,304 GB','Remote block storage; no local data disk in this shape','1 × 100 Gbps NIC; Internet egress and block storage priced separately','Select a region and availability domain that supports E5 bare metal',['https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm','https://www.oracle.com/cloud/compute/pricing/'],price_kind='current_rate_not_captured',ram_gb=2304,notes='A 2023 launch price was not assumed current in September 2026. OCPU meaning is shape/architecture dependent: preserve the vendor unit rather than imposing one universal conversion.')
add('Alibaba Cloud','alibabacloud.com','Elastic Bare Metal ecs.ebmg7.32xlarge','Regional ECS calculator / console pricing','Intel Xeon Platinum 8369B; 128 vendor vCPUs; 2.9 GHz / 3.5 GHz all-core turbo','512 GiB','Cloud ESSD storage, separately configured','64 Gbps instance network; 32 Gbps disk bandwidth; public Internet charging is separate','Exact region and zone must support this EBM instance family',['https://www.alibabacloud.com/help/en/ecs/user-guide/elastic-bare-metal-server-overview','https://www.alibabacloud.com/help/en/ecs/user-guide/create-an-ecs-bare-metal-instance'],price_kind='configurator_not_captured',notes='Physical single-tenant Elastic Bare Metal, not normal ECS VMs. Source overview updated August 17, 2026. Do not translate 128 vCPUs into 128 physical cores.')
add('Tencent Cloud','tencentcloud.com','Cloud Bare Metal (CBM)','Compute + system/data disks + network charged separately; console quote','Exact CBM physical-server model must be selected','Configure','Configure system/data disks','Separately billed networking; exact port and allowance not captured','Select a CBM-supported region; generic Tencent Cloud region map is not SKU availability',['https://www.tencentcloud.com/product/cbm','https://www.tencentcloud.com/document/product/1171/52407','https://www.tencentcloud.com/document/product/1171/52409'],price_kind='configurator_not_captured',notes='Physical bare-metal product confirmed; no matched current public configuration/price was captured. Do not seed invented host specifications.')
add('Huawei Cloud','huaweicloud.com','BMS physical.s4.xlarge (China pricing)','CNY 6,560/month estimated configuration price; checkout controls','Intel Skylake V5; 28 physical cores','192 GB','Cloud-disk capable; included disk capacity not established','10 Gigabit Ethernet NIC; public EIP/Internet bandwidth is a separate charge','China product catalog; exact region/zone must be selected',['https://www.huaweicloud.com/product/bms.html','https://www.huaweicloud.com/intl/en-us/product/bms.html','https://support.huaweicloud.com/intl/en-us/productdesc-bms/bms_01_0001.html'],amount=6560,currency='CNY',price_kind='estimated_configuration',cores=28,ram_gb=192,countries=['CN'],notes='Do not combine China CNY rates with international USD configurations. The 10 GE interface does not imply a free 10 Gbps public Internet connection.')
add('Shinjiru','shinjiru.com','E3 Premium — Malaysia','From USD 119.90/month','Intel Xeon E3; 4 cores; exact E3 model not stated','32 GB DDR4','2 × 2 TB enterprise HDD','Advertised 1 Gbps unmetered but plan lists Speed 300 Mbps; T&C apply','Malaysia','https://www.shinjiru.com/offshore-web-hosting/offshore-dedicated-server-business/',amount=119.90,currency='USD',price_kind='starting_price',cores=4,ram_gb=32,disk_gb=4000,unmetered=True,countries=['MY'],tier='configured',notes='Keep the 1 Gbps headline and 300 Mbps plan speed as distinct unresolved fields. No-setup wording includes a 12-month condition; do not assume monthly orders have no setup charge.')
add('i3D.net','i3d.net','bm9.hmm.12','From USD 213/month; varies by region','AMD EPYC 4464P; 12 cores / 24 threads; 3.75–5.40 GHz','128 GB DDR5','1.92 TB NVMe','Egress billed per GB: Europe USD 0.0021; North America 0.0030; Latin America 0.0107; APAC 0.0118; Oceania 0.0176; Middle East 0.0334; Africa 0.0468. Exact public port/commit requires order.','60+ advertised global sites; supported SKU/stock and rate differ by region',['https://www.i3d.net/bare-metal-servers/','https://www.i3d.net/global-bare-metal-servers/','https://www.i3d.net/bare-metal-cloud/'],amount=213,currency='USD',price_kind='global_starting_price_not_location_quote',cores=12,threads=24,ram_gb=128,disk_gb=1920,tier='configured',notes='Physical single tenant explicitly confirmed. Committed dedicated and hourly Bare Metal Cloud have different pricing modes. Provider backbone capacity is not per-server bandwidth.')
add('Gabia','gabiacloud.com','One-minute rental — HP DL160 Gen10 SSD','KRW 150,000/month, excluding VAT','Intel Xeon Bronze 3204; 6 cores; 1.9 GHz','16 GB DDR4','480 GB SSD + 1 TB SATA 7,200 RPM HDD','10 Mbps included circuit in plan; generic feature says 1 Gbps uplink. Extra contracted network/power/backup usage is billed.','South Korea; exact Gabia IDC site must be confirmed','https://idc.gabiacloud.com/server/onemin',amount=150000,currency='KRW',cores=6,ram_gb=16,disk_gb=1480,countries=['KR'],tax='Excludes VAT',tier='configured',notes='Pure hardware rental without term commitment or purchase requirement. Preserve 10 Mbps contracted allowance separately from 1 Gbps uplink; do not advertise 1 Gbps unlimited.')
add('IDCloudHost','idcloudhost.com','Bare Metal Dedicated Server','From IDR 2,500,000/month','Exact physical-server SKU requires sales/configurator','Configure','Configure','Quote port, domestic/international transfer and overages','Provider footprint includes Bogor, Jakarta and Cibitung ID, plus Singapore; dedicated SKU location must be quoted','https://idcloudhost.com/',amount=2500000,currency='IDR',price_kind='family_minimum_not_a_configured_offer',countries=['ID','SG'],notes='Homepage lists physical bare metal but retrieved minimum is not paired with a complete host configuration. Do not import third-party Xeon/RAM claims into this price.')
add('VinaHost','vinahost.vn','Xeon Quad Core E3 v1-2-3 Series Basic','USD 94.03/month advertised with 36-month selection; verify prepaid total','Intel Xeon E3-1230 v2; 4 cores / 8 threads; 3.3–3.7 GHz','8 GB DDR3','240 GB SSD OR 500 GB HDD; SSD selected for catalog example','Shared 100/10 Mbps displayed; unlimited transfer. Meaning of the two speed components must be confirmed.','Vietnam; exact physical city/facility to confirm','https://vinahost.vn/en/server/',amount=94.03,currency='USD',price_kind='36_month_equivalent_verify_checkout',cores=4,threads=8,ram_gb=8,disk_gb=240,unmetered=True,countries=['VN'],tier='configured',notes='Do not present the long-term equivalent as cancel-anytime monthly pricing. Preserve the split network label rather than silently assuming a 100 Mbps international circuit.')
add('Radore','radore.com','Dell R630 — 64 GB','USD 259/month','2 × Intel Xeon E5-2680 v4','64 GB','2 × 960 GB SSD','100 Mbps–1 Gbps unlimited Internet options; exact included selected port to confirm; 10 Gbps optional','Turkey; physical facility must be confirmed for the order','https://radore.com/services/dedicated',amount=259,currency='USD',ram_gb=64,disk_gb=1920,unmetered=True,countries=['TR'],tier='configured',notes='Do not treat the top of a configurable 100 Mbps–1 Gbps range as a guaranteed included port. /29 IP block advertised.')
add('Turhost','turhost.com','E65 Sunucu','Regular USD 219.77/month; first 3 months promotion USD 79.99/month','Intel Xeon Silver 4214R; 12 cores / 24 threads; 2.4–3.5 GHz','32 GB ECC','2 × 480 GB enterprise SSD; hardware RAID 1','1 Gbps exclusive port; 5,000 GB monthly transfer','Turkey; exact dedicated facility to confirm','https://www.turhost.com/sunucu/dedicated-server/',amount=219.77,currency='USD',price_kind='regular_rate_promotion_separate',cores=12,threads=24,ram_gb=32,disk_gb=960,port_mbps=1000,transfer_tb=5,countries=['TR'],tier='configured',notes='Budget the regular rate, not the 3-month incentive forever. RAID 1 is approximately 480 GB usable before filesystem overhead.')
add('Hosterion','hosterion.com','ds_IN!_v4','EUR 229/month unmanaged','Intel Xeon Gold; 44 cores / 88 threads; exact model not stated','64 GB','2 × 1 TB SSD','Public IPv4 and IPv6 /64; exact port and transfer allowance require quote','Dedicated facility not established by the retrieved product page; do not infer from Romanian headquarters','https://hosterion.com/dedicated-servers',amount=229,currency='EUR',cores=44,threads=88,ram_gb=64,disk_gb=2000,tier='configured',notes='Management is an additional EUR 125/month, not included. Country intentionally unknown until dedicated site confirmed.')
add('InMotion Hosting','inmotionhosting.com','Advanced Dedicated','USD 149.99/month on 12-month term; shown renewal USD 149.99','Intel Xeon E-2176G or specified equivalent; 6 cores / 12 threads','64 GB DDR4','2 × 1.92 TB SSD; software RAID 1','1 Gbps unmetered; 10 IPv4 addresses','Select available dedicated region; US offering used for this catalog example','https://www.inmotionhosting.com/dedicated-servers',amount=149.99,currency='USD',price_kind='12_month_commitment',cores=6,threads=12,ram_gb=64,disk_gb=3840,port_mbps=1000,unmetered=True,countries=['US'],tier='configured',notes='Region and management mode can change pricing; some selections show USD 179.99. CPU asterisk permits equivalent hardware. Verify root/reimage policy before using as a runner pool.',group='Investigate supply/company relationship with OpenMetal; do not assume independent')
add('DreamHost','dreamhost.com','Standard Dedicated — 16 GB','USD 165/month annual equivalent; annual prepayment','AMD EPYC; 6 physical cores; exact model unspecified','16 GB','480 GB SSD advertised, with RAID 1; drive count and raw-versus-usable capacity unresolved','Unmetered subject to policy; port speed not published in captured plan','US data centers; exact site must be confirmed',['https://www.dreamhost.com/hosting/dedicated/','https://help.dreamhost.com/hc/en-us/articles/215279658-Dedicated-server-overview'],amount=165,currency='USD',price_kind='annual_prepaid_equivalent',cores=6,ram_gb=16,unmetered=True,countries=['US'],tier='configured',notes='Managed physical server, not DreamCompute VM. Do not assume 480 GB raw when RAID display may describe usable capacity. Reimage can incur USD 100; verify current service terms.')
add('ServerPoint','serverpoint.com','Xeon E3-1275 v6','USD 79/month','Intel Xeon E3-1275 v6; 4 cores / 8 threads','32 GB DDR4','1 × 960 GB SSD','2 × 1 Gbps NIC; 70 TB monthly transfer; aggregated public throughput not assumed','Nevada and Texas US dedicated footprint; select SKU-specific site',['https://www.serverpoint.com/en/bare-metal-dedicated-server/all-dedicated-servers/','https://www.serverpoint.com/'],amount=79,currency='USD',cores=4,threads=8,ram_gb=32,disk_gb=960,transfer_tb=70,countries=['US'],tier='configured',notes='VDS products are excluded. Two NICs do not establish a 2 Gbps Internet entitlement.')
add('Psychz Networks','psychz.net','cMetal / Single CPU Xeon Dedicated','Live inventory / custom quote','Single/dual Xeon physical server; exact SKU required','Single-CPU family 16/32 GB options; selected configuration required','Up to 4 drive positions; installed drive capacity requires order','100 Mbps to 40 Gbps options; metered or unmetered; exact traffic package must be selected','Los Angeles, Dallas, Chicago, Atlanta, Ashburn US; São Paulo BR; London GB; Amsterdam NL; Moscow RU; Barcelona ES; Johannesburg ZA; Mumbai IN; Singapore SG; Taipei TW; Seoul KR; Tokyo JP; Sydney AU','https://www.psychz.net/dedicated-hosting.html',price_kind='configurator_not_captured',countries=['US','BR','GB','NL','RU','ES','ZA','IN','SG','TW','KR','JP','AU'],notes='These are dedicated-service location listings, not guaranteed inventory for every SKU. cVirtual is excluded; cMetal supports physical provisioning. Vendor private network and public transit are distinct.',group='Profuse Solutions / Psychz')
add('Sharktech','sharktech.net','Dedicated Servers','From USD 219/month; exact configured basket not captured','Physical dedicated hardware; select current inventory','Configure','Configure','1–40 Gbps family options; metered/unmetered terms depend on order','Provider location selector; exact dedicated sites must be verified',['https://sharktech.net/','https://sharktech.net/dedicated-servers/'],amount=219,currency='USD',price_kind='family_minimum_not_a_configured_offer',notes='Do not confuse 40/100 Gbps backbone links with each server public port. Dynamic inventory did not expose a matched current configuration.')
add('Adentro Tecnologia','adentro.com.br','Servidor Dedicado Bare Metal','From BRL 1,490/month','Custom physical-server configuration','Quote','Quote','Contract-specific Internet/transfer','Brazil; exact facility and region must be quoted','https://adentro.com.br/',amount=1490,currency='BRL',price_kind='family_minimum_not_a_configured_offer',countries=['BR'],notes='Brazilian Adentro Tecnologia, not the unrelated US marketing company at adentro.com. Office addresses and data-center partner logos are not evidence of a selected host location.')
add('ServerPronto','serverpronto.com','Power — Xeon E3-1230 v2','USD 59.95/month','Intel Xeon E3-1230 v2; 4 cores / 8 threads; 3.3 GHz','16 GB DDR3','240 GB SSD','10 TB transfer; selected public port requires confirmation','US dedicated service; exact physical facility must be confirmed','https://www.serverpronto.com/dedicated',amount=59.95,currency='USD',cores=4,threads=8,ram_gb=16,disk_gb=240,transfer_tb=10,countries=['US'],tier='configured',notes='Legacy CPU intentionally retained as a real low-cost class; do not equate its four cores with modern EPYC cores.')

# Post-research corrections / unit preservation.
by_id={r['id']:r for r in records}
r=by_id['idc-frontier']
r.update(product='Standard 2P32C256GB',price_display='JPY 115,000/month; setup JPY 0; excluding tax',evidence='configured',notes='East Japan 1 has redundant 1 Gbps interfaces; East Japan 2/3 redundant 10 Gbps. Internal storage options are 400 GB RAID 1 or 2,400 GB RAID 5 using SAS SSDs and hot spare; exact included selection must be checked. 21+ nodes requires sales consultation. Hardware and stock may vary; no CPU/RAM/disk changes after order.')
r['price'].update(amount=115000,currency='JPY',kind='advertised_configuration',setup_amount=0,tax_basis='Excludes tax')
r['cpu'].update(display='2 × 16-core processors; exact CPU model not stated',physical_cores_total=32)
r['memory'].update(display='256 GB',capacity_vendor_gb=256)
r['storage']['display']='400 GB RAID 1 or 2,400 GB RAID 5 internal SAS SSD; raw disk count not established'
r['network']['display']='Redundant 1 Gbps (East Japan 1) or 10 Gbps (East Japan 2/3); best-effort shared network; transfer billing not established'
r['locations'].update(display='Fukushima Shirakawa Data Center, Japan; East Japan 1/2/3 service regions',scope='Bare-metal pricing page identifies the facility; region-specific interfaces')
r=by_id['servermania']; r['source_urls'].append('https://www.servermania.com/kb/articles/dedicated-server-hosting-pricing')
r['storage'].update(display='1 TB NVMe M.2',raw_capacity_vendor_gb=1000)
r['network'].update(display='1 Gbps port; 100 TB transfer in provider pricing guide example',public_port_mbps=1000,included_transfer_tb=100)
for key,capacity,vcpu in [('amazon-web-services',384,96),('alibaba-cloud',512,128)]:
    r=by_id[key]; r['memory'].update(capacity_vendor_gb=None,capacity_gib=capacity,byte_basis='Explicit GiB in vendor specification')
    r['cpu']['vendor_vcpu_count']=vcpu
by_id['oracle-cloud']['cpu']['vendor_ocpu_count']=192
by_id['turhost']['storage']['usable_capacity_gb']=480
assert len(records)==90, len(records)

# Final first-party offer detail checks; values remain snapshots, not live orders.
r=by_id['clouvider']
r.update(product='Preconfigured E3-1240 v5, London — SSD',price_display='USD 74/month in the final USD locale; earlier EUR locale displayed EUR 64',evidence='configured',notes='Price is locale/currency-specific, not a USD-to-EUR conversion. The 50 TB allowance is not unmetered. Other dedicated regions include Manchester, Amsterdam, Frankfurt and seven US metros; this price/configuration is London.')
r['price'].update(amount=74,currency='USD',kind='advertised_configuration')
r['cpu'].update(display='Intel Xeon E3-1240 v5; 4 cores / 8 threads; 3.5 GHz',physical_cores_total=4,hardware_threads_total=8)
r['memory'].update(display='16 GB DDR4 ECC',capacity_vendor_gb=16)
r['storage'].update(display='1 × 240 GB SSD',raw_capacity_vendor_gb=240)
r['network'].update(display='1 Gbps NIC; 50 TB monthly data transfer',public_port_mbps=1000,included_transfer_tb=50,unmetered=False)
r['locations'].update(display='London, United Kingdom',country_codes=['GB'],scope='Preconfigured offer explicitly names London')
r['source_urls']=['https://www.clouvider.com/dedicated-servers/']

r=by_id['interserver']
r.update(product='Buy It Now — 2 × Xeon E5-2680 v4 8SFF, SATA storage',price_display='USD 236/month; zero setup fees advertised',evidence='configured',notes='NYC-region stocked offer, not the USD 213 NVMe variant. Other dedicated metros are Dallas and Los Angeles; hardware varies. Stock listings and a generic sold-out notice coexist, so availability is not guaranteed.')
r['price'].update(amount=236,currency='USD',kind='advertised_configuration',setup_amount=0)
r['cpu'].update(display='2 × Intel Xeon E5-2680 v4; 28 total physical cores',physical_cores_total=28,hardware_threads_total=None)
r['memory'].update(display='128 GB',capacity_vendor_gb=128)
r['storage'].update(display='2 × 24 TB SATA HDD',raw_capacity_vendor_gb=48000)
r['network'].update(display='1 Gbps unmetered; 1 VLAN IP (/30) advertised',public_port_mbps=1000,unmetered=True)
r['locations'].update(display='NYC metro region, US',country_codes=['US'],scope='Selected stocked offer names NYC region, not an exact facility')
r['source_urls']=['https://www.interserver.net/dedicated/']

r=by_id['reliablesite']
r.update(product='AMD Ryzen 5600X 64GB Rapid Deploy',price_display='USD 129/month',evidence='configured',notes='Inventory snapshot names Miami for this exact configuration. Provider also lists NYC, Los Angeles, Dallas, Amsterdam and Querétaro, but that is not universal SKU stock. Port wording conflicts: free 10 Gbps versus Metal+ conditional; retain the clear 1 Gbps service entitlement, leave physical port unknown. Ignore erroneous DDR5 upsell text for Ryzen 5600X.')
r['price'].update(amount=129,currency='USD',kind='advertised_configuration')
r['cpu'].update(display='AMD Ryzen 5600X; 6 cores / 12 threads; 3.7 GHz',physical_cores_total=6,hardware_threads_total=12)
r['memory'].update(display='64 GB DDR4; non-ECC',capacity_vendor_gb=64)
r['storage'].update(display='1 × 512 GB NVMe; no RAID',raw_capacity_vendor_gb=512)
r['network'].update(display='1 Gbps unmetered service; up-to-10-Gbps port wording depends on Metal+ and is inconsistent',public_port_mbps=None,service_rate_mbps=1000,unmetered=True)
r['locations'].update(display='Miami, Florida, US in selected inventory row',country_codes=['US'],scope='Inventory row for selected configuration')
r['source_urls']=['https://www.reliablesite.net/dedicated-servers/','https://www.reliablesite.net/dedicated-servers/6-core-server/amd-ryzen-5600x-64GB']

r=by_id['adentro-tecnologia']
r.update(product='Dedicado Light',price_display='BRL 890/month on product page; older homepage minimum BRL 1,490 differs',evidence='configured',notes='Brazilian Adentro, not adentro.com. Selected product price supersedes homepage family minimum for this record; confirm commercial terms. Pure Storage all-flash allocation is remote/shared storage capacity, not another local physical disk. Network page says “1 GB”; its speed unit is ambiguous.')
r['price'].update(amount=890,currency='BRL',kind='advertised_configuration_with_page_discrepancy')
r['cpu'].update(display='2 × Xeon E5-2680 v4; 28 cores / 56 threads',physical_cores_total=28,hardware_threads_total=56)
r['memory'].update(display='64 GB DDR4',capacity_vendor_gb=64)
r['storage'].update(display='2 × 100 GB SSD RAID 1 for OS, plus 250 GB Pure Storage all-flash allocation',raw_capacity_vendor_gb=200,remote_block_capacity_gb=250,usable_capacity_gb=100)
r['network'].update(display='Literal “1 GB com tráfego ilimitado”; unlimited transfer, speed unit requires confirmation',public_port_mbps=None,unmetered=True)
r['locations'].update(display='Brazil; product confirms national data centers, not an exact selected city',country_codes=['BR'],scope='Country-only physical-service confirmation')
r['source_urls']=['https://adentro.com.br/solucoes/servidor-dedicado/','https://adentro.com.br/']

r=by_id['keyweb']
r.update(product='Keymachine KM i7 | 32 GB',price_display='EUR 74/month + EUR 119 setup; German consumer prices include 19% VAT',evidence='configured',notes='Minimum contract one month; 14-day end-of-term notice. RAM/drive upgrades are separate charges. Dedicated VPS is not this physical product. RAID 1 usable capacity is about 250 GB before overhead. Transfer row is blank in parsed comparison; do not silently call it unlimited.')
r['price'].update(amount=74,currency='EUR',kind='advertised_configuration',setup_amount=119,tax_basis='Includes 19% German VAT; other EU country tax may differ')
r['cpu'].update(display='Intel Core i7-8700; 6 physical cores; up to 4.6 GHz',physical_cores_total=6)
r['memory'].update(display='32 GB DDR4',capacity_vendor_gb=32)
r['storage'].update(display='2 × 250 GB SATA SSD; software RAID 1',raw_capacity_vendor_gb=500,usable_capacity_gb=250)
r['network'].update(display='1 Gbps switch port; 1 IPv4 and 1 IPv6; transfer allowance unresolved',public_port_mbps=1000,unmetered=None)
r['locations'].update(display='Germany; exact facility must be confirmed',country_codes=['DE'],scope='Dedicated physical service explicitly in Germany')
r['source_urls']=['https://www.keyweb.de/en/server/dedicated-root-server/dedicated-basic-server']

r=by_id['fasthosts']
r.update(product='Xeon-E-32-NVMe',price_display='GBP 100/month discounted; displayed regular GBP 115; promotion term needs checkout',evidence='configured',notes='Landing-page “from GBP 25” is not the selected configuration. Limited-stock message displayed. Port hardware family supports dual GbE/10GbE variants; no included per-SKU Internet speed inferred. RAM/storage are not family maximums.')
r['price'].update(amount=100,currency='GBP',kind='discounted_configuration_terms_unverified')
r['cpu'].update(display='Intel Xeon E-2356G; 6 cores; 3.2 GHz',physical_cores_total=6)
r['memory'].update(display='32 GB DDR4 ECC',capacity_vendor_gb=32)
r['storage'].update(display='2 × 512 GB NVMe; software RAID 1',raw_capacity_vendor_gb=1024,usable_capacity_gb=512)
r['network'].update(display='Unlimited transfers; exact included public port speed requires order confirmation',public_port_mbps=None,unmetered=True)
r['locations'].update(display='United Kingdom; exact dedicated data center to confirm',country_codes=['GB'],scope='UK dedicated service')
r['source_urls']=['https://www.fasthosts.co.uk/dedicated-servers/cheap','https://www.fasthosts.co.uk/dedicated-servers']

# Contabo first-party indexed card supplies base RAM and storage, but checkout is blocked.
r=by_id['contabo']
r['cpu']['display']='AMD Ryzen 9 7900; 12 physical cores; 3.7 GHz'
r['memory'].update(display='64 GB base; up to 128 GB as an upgrade',capacity_vendor_gb=64)
r['storage'].update(display='1 TB NVMe base; upgrades separate',raw_capacity_vendor_gb=1000)
r['notes']+=' First-party indexed product card identifies Ryzen 9 7900, 64 GB and 1 TB NVMe; final direct fetch was HTTP 403. Revalidate the complete promotional basket.'
r['source_urls'].append('https://contabo.com/')

# Numerical refinements that are explicitly stated in the corresponding source narrative.
by_id['ikoula']['network']['committed_mbps']=100
by_id['ionos']['storage']['usable_capacity_gb']=1000
by_id['inmotion-hosting']['storage']['usable_capacity_gb']=1920
by_id['hetzner']['evidence']='configured'
for r in records:
    r['offer_id']=r['id']+'--example-2026-09-16'
    r['art_source_page']=r['source_urls'][0]
    r['physical_chassis_model']=None
    r['exact_facility_verified']=False
assert len(records)==90 and len({r['id'] for r in records})==90

r=by_id['ransomit']
r.update(product='ME2-E-2136-64GB-2x500GBNVME-10G',price_display='USD 165/month in selected USD storefront',evidence='configured',notes='Product row explicitly says Equinix ME2 although the category heading says ME1; selected row wins provisionally and must be confirmed. USD is explicit; do not assume AUD. One unit shown available, not a bulk reservation. Other city catalogs have separate hardware and prices.')
r['price'].update(amount=165,currency='USD',kind='advertised_configuration')
r['cpu'].update(display='Intel Xeon E-2136; 6 cores; 3.3 GHz',physical_cores_total=6)
r['memory'].update(display='64 GB',capacity_vendor_gb=64)
r['storage'].update(display='2 × 500 GB NVMe',raw_capacity_vendor_gb=1000)
r['network'].update(display='10 Gbps port; 20 TB monthly data; 1 IPv4 and IPv6 /64',public_port_mbps=10000,included_transfer_tb=20,unmetered=False)
r['locations'].update(display='Melbourne, Australia; selected product says Equinix ME2',country_codes=['AU'],scope='Product-row site; category-header ME1 discrepancy recorded')
r['source_urls']=['https://secure.ransomit.com.au/index.php?rp=/store/melbourne-dedicated-servers','https://www.ransomit.com.au/']
r['art_source_page']=r['source_urls'][0]

r=by_id['digital-pacific']
r.update(product='X-C6620-2 — Dell PowerEdge C6620 node',price_display='AUD 473/month displayed; billing-cycle widget contains inconsistent equivalent figures, so checkout must confirm',evidence='configured',notes='Australian storefront; confirm currency and tax. Use the primary displayed rate, not the contradictory half/third-price widget equivalents. Dedicated physical compute node in shared blade chassis; shared chassis remains a failure domain. Stock is only a snapshot.')
r['price'].update(amount=473,currency='AUD',kind='displayed_rate_billing_widget_discrepancy')
r['cpu'].update(display='2 × Intel Xeon Gold 5415+; 16 total physical cores; 2.9 GHz',physical_cores_total=16)
r['memory'].update(display='64 GB DDR5',capacity_vendor_gb=64)
r['storage'].update(display='4 × 480 GB SSD; RAID 10; advertised usable 960 GB',raw_capacity_vendor_gb=1920,usable_capacity_gb=960)
r['network'].update(display='5 TB monthly transfer; public port speed requires confirmation',included_transfer_tb=5)
r['locations'].update(display='Sydney, Australia',country_codes=['AU'],scope='Dedicated page explicitly locates its server fleet in Sydney')
r['source_urls']=['https://www.digitalpacific.com.au/dedicated/dedicated-servers/']
r['physical_chassis_model']='Dell PowerEdge C6620 node in C6600 chassis'
r['art_source_page']=r['source_urls'][0]
